### ISSUE TITLE
Is something like this possible?

### ISSUE THREAD

**Issue by dfischer** [carlhuda/janus#461]
When viewing a SCSS/Sass file show the selector path in the status bar of the file?

E.g

``` scss
.page-footer {
  .events {
    @include column(3);
    @include mobileColumn(4);

    float: right;

    @include respondTo(smallScreen) {
      float: none;
    }

    .events-title {
      font-size: ms(3);
    }

    .events-past-title {
      font-size: ms(2);
    }

    .event {
      @include mobileColumn(4);
       .nested-example here {
       }
    }
}
```

If you were inside "nested-example-here" the vim status bar would show `page-footer > event > .nested-example here`

Is this possible?
